//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetCellID.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.GetCellIdSoap")]
    public interface GetCellIdSoap {
        
        // CODEGEN: Generating message contract since element name msisdn from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCellID", ReplyAction="*")]
        GetCellID.ServiceReference1.GetCellIDResponse GetCellID(GetCellID.ServiceReference1.GetCellIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCellIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCellID", Namespace="http://tempuri.org/", Order=0)]
        public GetCellID.ServiceReference1.GetCellIDRequestBody Body;
        
        public GetCellIDRequest() {
        }
        
        public GetCellIDRequest(GetCellID.ServiceReference1.GetCellIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCellIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string msisdn;
        
        public GetCellIDRequestBody() {
        }
        
        public GetCellIDRequestBody(string msisdn) {
            this.msisdn = msisdn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCellIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCellIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetCellID.ServiceReference1.GetCellIDResponseBody Body;
        
        public GetCellIDResponse() {
        }
        
        public GetCellIDResponse(GetCellID.ServiceReference1.GetCellIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCellIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCellIDResult;
        
        public GetCellIDResponseBody() {
        }
        
        public GetCellIDResponseBody(string GetCellIDResult) {
            this.GetCellIDResult = GetCellIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetCellIdSoapChannel : GetCellID.ServiceReference1.GetCellIdSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCellIdSoapClient : System.ServiceModel.ClientBase<GetCellID.ServiceReference1.GetCellIdSoap>, GetCellID.ServiceReference1.GetCellIdSoap {
        
        public GetCellIdSoapClient() {
        }
        
        public GetCellIdSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetCellIdSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetCellIdSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetCellIdSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetCellID.ServiceReference1.GetCellIDResponse GetCellID.ServiceReference1.GetCellIdSoap.GetCellID(GetCellID.ServiceReference1.GetCellIDRequest request) {
            return base.Channel.GetCellID(request);
        }
        
        public string GetCellID(string msisdn) {
            GetCellID.ServiceReference1.GetCellIDRequest inValue = new GetCellID.ServiceReference1.GetCellIDRequest();
            inValue.Body = new GetCellID.ServiceReference1.GetCellIDRequestBody();
            inValue.Body.msisdn = msisdn;
            GetCellID.ServiceReference1.GetCellIDResponse retVal = ((GetCellID.ServiceReference1.GetCellIdSoap)(this)).GetCellID(inValue);
            return retVal.Body.GetCellIDResult;
        }
    }
}
